### ISSUE TITLE
ROS2 version for gazebo_grasp_plugin

### ISSUE THREAD

**Issue by AlezzzRd** [JenniferBuehler/gazebo-pkgs#57]
Hi Jennifer, 

Do you have a plan to develop a ros2 version for this very useful gazebo_grasp_plugin?

Thanks

**Comment by JenniferBuehler** [comment]
Hi,
Yes I would like to migrate all my packages to ros2, however I don't know how soon I will be able to make time for it.

The grasp plugin itself is ROS independent though, it only depends on gazebo. You will only need to tweak the cmake file which uses catkin to get rid of ROS dependencies.

**Comment by kongoncharuk** [comment]
Hi @JenniferBuehler . I've migrated gazebo_grasp_plugin and gazebo_version_helpers (as grasp_plugin was depending on it) to ROS2 humble here: https://github.com/kongoncharuk/gazebo-pkgs/tree/humble. 

Could you perhaps create a "humble" branch in your repository so that I can create a pull request into it?

**Comment by JenniferBuehler** [comment]
Awesome thanks for doing that! I will create the branch

**Comment by JenniferBuehler** [comment]
I branched it off master, but thinking probably it should be noetic. What did you base yours on?
